In [1]:
import numpy as np

# 1 -- > Eigenvalues and Eigenvectors of an array

## Syntax :

numpy.linalg.eig()

## Code :

In [2]:
m = np.mat(" 13 , 22 , 34 ; 48 , 55 , 62 ; 79 , 81 , 96 ")

In [3]:
m

matrix([[13, 22, 34],
        [48, 55, 62],
        [79, 81, 96]])

In [4]:
e_val , e_vec = np.linalg.eig(m)

In [5]:
e_val

array([172.61664505, -11.53226074,   2.91561569])

In [6]:
e_vec

matrix([[ 0.24592122,  0.83715572,  0.33663135],
        [ 0.52863227, -0.10346784, -0.83297   ],
        [ 0.81244734, -0.53708911,  0.43913588]])

# 2 -- > np.digitize() :

## Syntax :
np.digitize( array , bin ,right )

right --> Optional

## Code :

In [7]:
arr = np.array([10,34,12,23,8,18,29,41,32,11])

In [8]:
arr

array([10, 34, 12, 23,  8, 18, 29, 41, 32, 11])

In [9]:
np.digitize( arr , bins = [10,20,30])

array([1, 3, 1, 2, 0, 1, 2, 3, 3, 1], dtype=int64)

In [10]:
arr = np.array([10,34,54,13,76,24,78,13,96,24,67,23,51,67,23])

In [11]:
arr

array([10, 34, 54, 13, 76, 24, 78, 13, 96, 24, 67, 23, 51, 67, 23])

In [12]:
bins = np.array([15,30,45,60])

In [13]:
result = np.digitize( arr , bins , right = True)

In [14]:
result

array([0, 2, 3, 0, 4, 1, 4, 0, 4, 1, 4, 1, 3, 4, 1], dtype=int64)

# 3-->np.repeat()


## Syntax :
   np.repeat( a , repeating amount , axis=None )#axis-->Optional

## Code:

In [15]:
arr = np.array([11,12,13,14,15])

In [16]:
arr

array([11, 12, 13, 14, 15])

In [17]:
arr1 = np.repeat(arr,3)
arr1

array([11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15])

In [18]:
arr2 = np.array([[10,20,30],[40,50,60]])

In [20]:
arr3 = np.repeat(arr2,2,axis=0)#Using axis , axis = 0(for row-wise repeatation)/1(for colomn-wise repeatation)
arr3

array([[10, 20, 30],
       [10, 20, 30],
       [40, 50, 60],
       [40, 50, 60]])

##  Application :
 It can be used to repeat when array elements are same througout a 2D array

# 4 -- > np.squeeze()

## Syntax :
np.squeeze( array , axis )

axis --> Optional

## Code :

In [21]:
arr = np.array([[[10,20,30],[40,50,60],[70,80,90]]])

In [22]:
arr.shape

(1, 3, 3)

In [24]:
result = np.squeeze(arr)

In [26]:
print(result)
print(result.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


# 5--> np.linspace()

## Syntax:
   np.linspace( start_value , stop_value , number of samples , endpoint , retstep , dtype , axis )
   
   endpoint,retstep,dtype,axis --> Optional 

In [27]:
arr = np.linspace(0,2,15)
arr

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [28]:
arr1 = np.linspace(0,2,15,retstep=True)#retstep returns the difference between two adjacent elements
arr1

(array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
        0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
        1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ]),
 0.14285714285714285)

In [29]:
arr2 = np.linspace(0,2,15,endpoint=True)
arr2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Application :
  It is used for plotting graphs where the array can be given as input and converted into their sin , cos , tan etc and resultant graph can be plotted

#  6 -- > np.clip() :

## Syntax :
np.clip( array , a_min , a_max , out = None )

## Code :


In [30]:
arr = np.arange(0,20,3)
print(arr)

[ 0  3  6  9 12 15 18]


In [32]:
result = np.clip(arr , 5 ,11)# anything below 5 is replaced with 5 and anything above 11 are replaced with 11
print(result)

[ 5  5  6  9 11 11 11]


# 7 -- > np.extract()

## Syntax :
np.extract( condition , array )

## Code :

In [33]:
arr = np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
result = np.extract((arr % 3 == 0) & (arr > 5),arr)
result

array([ 6,  9, 12])

In [35]:
arr = np.arange(40).reshape(8,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [36]:
condition = np.mod(arr,5) == 0 
result = np.extract(condition , arr)

In [37]:
result

array([ 0,  5, 10, 15, 20, 25, 30, 35])

## Application :
It can be used to extract certain values from the array when the specified condition is satisfied.

# 8 -- > np.argpartition() :

## Synatx :
np.argpartution( array , kth , axis , kind , order )

axis , kind , order --> Optional

## Code :


In [38]:
arr = np.array ([1,4,7,2,9,6])
np.argpartition(arr,4)

array([3, 0, 1, 5, 2, 4], dtype=int64)

# 9 -- > np.setdiff1d()

## Syntax :

np.setdiff1d( array_1 , array_2 , assume_unique )

## Code :


In [40]:
arr1 = np.arange(5,50,5)
print(arr1)
arr2 = np.arange(0,50,10)
print(arr2)

[ 5 10 15 20 25 30 35 40 45]
[ 0 10 20 30 40]


In [41]:
result = np.setdiff1d(arr1,arr2)
print(result)

[ 5 15 25 35 45]


## 10 -- > np.itemsize()

## Syntax :
array_name.itemsize

## Code :

In [42]:
arr1 = np.array([[32,45,67],[342,12,65]])
print(arr1.itemsize)

4


In [43]:
arr2 = np.array([[32,45,67],[342,12,65]],dtype =np.float)
print(arr2.itemsize)

8


In [44]:
arr3 = np.array([[32,45,67],[342,12,65]],dtype =np.complex)
print(arr3.itemsize)

16


# 11-->np.hstack()

## Syntax :
 np.hstack(input_array)

## Code :

In [3]:
arr1 = np.arange(6).reshape(3,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
arr2 = np.arange(7,13).reshape(3,2)
arr2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [9]:
arr3 = np.arange(14,20).reshape(3,2)
arr3

array([[14, 15],
       [16, 17],
       [18, 19]])

In [8]:
result = np.hstack((arr1,arr2,arr3))
result

array([[ 0,  1,  7,  8, 14, 15],
       [ 2,  3,  9, 10, 16, 17],
       [ 4,  5, 11, 12, 18, 19]])

# 12 -- > np.vstack()

## Syntax :
np.vstack(input_array)

## Code :

In [48]:
arr1 = np.arange(6).reshape(3,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
arr2 = np.arange(7,13).reshape(3,2)
arr2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [50]:
result = np.vstack((arr1,arr2))
result

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# 13 --> np.hsplit() :

## Syntax :
np.hsplit( array , number of horizontal sections ) 

## Code :

In [51]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [52]:
result = np.hsplit( arr , 3)
result

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

## Application :
 It can be used when we need to split an array or dataframe into multiple sub-arrays colomns wise.

# 14 -- > np.vsplit()

## Syntax :
np.vsplit( array , number of vertical sections )

## Code :

In [53]:
arr = np.arange(40).reshape(8,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [56]:
result = np.vsplit( arr , 4 )
result

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])]

In [58]:
result = np.vsplit( arr , np.array([4,7]) )
result

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]]),
 array([[35, 36, 37, 38, 39]])]

## Application :
 It can be used when we need to split an array or dataframe into multiple sub-arrays row wise.

# 15 -- > View vs Shallow copy :

# Shallow copy :
# Syntax :

array_name.copy(  )

## Code :

In [59]:
arr1 = np.array([10,20,30,40,50])

In [60]:
x = np.copy(arr1)

In [61]:
arr1

array([10, 20, 30, 40, 50])

In [62]:
x

array([10, 20, 30, 40, 50])

In [63]:
x[3] = 70

In [64]:
x # here the changes are applied since it is a new array

array([10, 20, 30, 70, 50])

In [65]:
arr1 # changed made in copied array does not affect original array

array([10, 20, 30, 40, 50])

In [66]:
print(arr1.base)
print(x.base)

None
None


base attribute is used to find whether the variable hold the data 

In this case since we used copy() both arr1 and x hold their respective data which in turn return None on both the cases

## View :

## Syntax :
array_name.view()

## Code :

In [67]:
arr2 = np.arange(10)

In [68]:
y = arr2.view()
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
y[5] = 10
y 

array([ 0,  1,  2,  3,  4, 10,  6,  7,  8,  9])

In [70]:
arr2 # since y is a reference to arr2 it automatically updates the changes made to arr2  

array([ 0,  1,  2,  3,  4, 10,  6,  7,  8,  9])

In [71]:
print(arr2.base)
print(y.base)

None
[ 0  1  2  3  4 10  6  7  8  9]


In this case arr2.base return none since it hold the data and y.base return the array since it is just a reference as a result of view()

# 16 -- > Deep Copy :

## Syntax :
copy.deepcopy( array )

## Code :

In [72]:
import copy
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = copy.deepcopy( arr1 )

In [73]:
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [74]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [75]:
arr2[1][2] = 70 

In [76]:
arr2

array([[10, 20, 30],
       [40, 50, 70]])

In [77]:
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In deep copy any change made to the copied list does not affect the original list.

# 17 -- >np.copy() :


## Syntax :
np.copy( array , order ,  sublook )
  
order --> {'C','F','A','K'} --> Optional

sublook -- > Optional

## Code :


In [78]:
arr1 = np.array([[10,20,30],[40,50,60]])
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [79]:
arr2 = np.copy(arr1)
arr2

array([[10, 20, 30],
       [40, 50, 60]])

# 18 -- > np.meshgrid()

## Syntax :
np.meshgrid( *xi , copy , sparse , indexing  )

copy , sparse , indexing  --> Optional

## Code :

In [80]:
x = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
y = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5] 
x1,y1 = np.meshgrid(x,y)

In [81]:
x1

array([[-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [82]:
y1

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5]])

# 19 -- > np.swapaxes() :

## Syntax :
np.swapaxes( array , axis1 , axis2 )

## Code :

In [83]:
arr = np.arange(20).reshape(4,5)

In [84]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
result = np.swapaxes(arr,1,0)
result

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [87]:
arr = np.arange(40).reshape(2,5,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [88]:
result = np.swapaxes(arr,2,0)
result

array([[[ 0, 20],
        [ 4, 24],
        [ 8, 28],
        [12, 32],
        [16, 36]],

       [[ 1, 21],
        [ 5, 25],
        [ 9, 29],
        [13, 33],
        [17, 37]],

       [[ 2, 22],
        [ 6, 26],
        [10, 30],
        [14, 34],
        [18, 38]],

       [[ 3, 23],
        [ 7, 27],
        [11, 31],
        [15, 35],
        [19, 39]]])

# 20 -- > np.colomn_stack() :


## Syntax :
np.colomn_stack( array )

## Code :

In [89]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

In [90]:
result = np.column_stack((arr1,arr2))
result

array([[10, 40],
       [20, 50],
       [30, 60]])

In [91]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [92]:
result = np.column_stack((arr1,arr2))
result

array([[10, 20, 30,  5, 10, 15],
       [40, 50, 60, 20, 25, 30],
       [70, 80, 90, 35, 40, 45]])